apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tls-secret
  namespace: traefik-gateway
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: digitalnucleus-store
    kind: ClusterSecretStore
  target:
    name: vmstar.lan
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: tls-secret
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: tls-secret
        property: tls.key
