apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: header-matching
  namespace: nginx-app-gateway
  labels:
    httproute: header-match
spec:
  parentRefs:
  - kind: Gateway
    name: traefik-gateway
    namespace: traefik-gateway
  hostnames:
  - "nginx-gateway.vmstar.lan"
  rules:
  - matches:
    - headers:
      - type: RegularExpression
        name: User-Agent
        value: ".*(Android|iPhone|iPad|iPod).*"
    backendRefs:
      - name: mobile-svc
        port: 80



