apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: method-matching
  namespace: nginx-app-gateway
  labels:
    httproute: method-match
spec:
  parentRefs:
  - kind: Gateway
    name: traefik-gateway
    namespace: traefik-gateway
  hostnames:
    - "nginx-gateway.vmstar.lan"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api/v2
      method: GET
    backendRefs:
      - name: api-v2
        port: 9001
