apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: request-header-modifier
  namespace: nginx-app-gateway
  labels:
    httproute: request-header-modifier
spec:
  parentRefs:
    - kind: Gateway
      name: traefik-gateway
      namespace: traefik-gateway
  hostnames:
    - "nginx-gateway.vmstar.lan"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /test
    filters:
      - type: RequestHeaderModifier
        requestHeaderModifier:
          set:
            - name: Authorization
              value: "Basic YWRtaW46cGFzc3dvcmQ="
    backendRefs:
    - name: api-svc
      port: 9004
