apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: traffic-split
  namespace: nginx-app-gateway
  labels:
    httproute: traffic-split
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik-gateway
  hostnames:
    - "nginx-gateway.vmstar.lan"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: blue-svc
      port: 80
      weight: 50
    - name: green-svc
      port: 80
      weight: 50

